[package]
name = "ezgfx-examples"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ezgfx = { path = "../ezgfx" }