[package]
name = "ezgfx-core"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

[dependencies]
image = "0.23.4"
winit = "0.22.2"
wgpu = "0.5.0"
glsl-to-spirv = "0.1"
futures = "0.3.5"
bytemuck = "1.2.0"
cgmath = "0.17"
glsl = "4.0.3"