[package]
name = "ezgfx-derive"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ezgfx-core = { path = "../ezgfx-core" }
proc-macro2 = "1.0"
quote = "1.0.6"
syn = "1.0.22"