[package]
name = "ezgfx-derive"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ezgfx-core = { path = "../ezgfx-core" }
spirv-reflect = "0.2.3"
Inflector = "0.11.4"
proc-macro2 = "1.0"
shaderc = "0.6.2"
quote = "1.0.6"
syn = "1.0.22"