[package]
name = "macros"
version = "0.1.0"
authors = ["_nahoy <42898627+NahoyGames@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.6"
syn = "1.0.22"